# Navigation and Base Settings
BaseUrl=https://homeloans.hdfc.bank.in/

# Loan Calculator Locators
loanAmt=loan-amt-inp
tenure=tenure-inp
rate=rate-inp
emiDisplay=monthly-emi
interestDisplay=interest-amt
principalDisplay=principal-amt


# ... existing locators ...
calcHeading=//h2[contains(@class, 'cmp-title__text') and contains(text(), 'Calculate Your Home Loan')]